# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/zhuelly/Project/GodotProject/elly_videoplayer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/zhuelly/Project/GodotProject/elly_videoplayer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/zhuelly/Project/GodotProject/elly_videoplayer/CMakeFiles /media/zhuelly/Project/GodotProject/elly_videoplayer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/zhuelly/Project/GodotProject/elly_videoplayer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /media/zhuelly/Project/GodotProject/elly_videoplayer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GDExtensionTemplate

# Build rule for target.
GDExtensionTemplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GDExtensionTemplate
.PHONY : GDExtensionTemplate

# fast build rule for target.
GDExtensionTemplate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/build
.PHONY : GDExtensionTemplate/fast

#=============================================================================
# Target rules for targets named templates

# Build rule for target.
templates: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 templates
.PHONY : templates

# fast build rule for target.
templates/fast:
	$(MAKE) $(MAKESILENT) -f templates/CMakeFiles/templates.dir/build.make templates/CMakeFiles/templates.dir/build
.PHONY : templates/fast

#=============================================================================
# Target rules for targets named godot-cpp

# Build rule for target.
godot-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 godot-cpp
.PHONY : godot-cpp

# fast build rule for target.
godot-cpp/fast:
	$(MAKE) $(MAKESILENT) -f godot-cpp/CMakeFiles/godot-cpp.dir/build.make godot-cpp/CMakeFiles/godot-cpp.dir/build
.PHONY : godot-cpp/fast

src/src/AVDecoderHandler.o: src/src/AVDecoderHandler.cpp.o
.PHONY : src/src/AVDecoderHandler.o

# target to build an object file
src/src/AVDecoderHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/AVDecoderHandler.cpp.o
.PHONY : src/src/AVDecoderHandler.cpp.o

src/src/AVDecoderHandler.i: src/src/AVDecoderHandler.cpp.i
.PHONY : src/src/AVDecoderHandler.i

# target to preprocess a source file
src/src/AVDecoderHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/AVDecoderHandler.cpp.i
.PHONY : src/src/AVDecoderHandler.cpp.i

src/src/AVDecoderHandler.s: src/src/AVDecoderHandler.cpp.s
.PHONY : src/src/AVDecoderHandler.s

# target to generate assembly for a file
src/src/AVDecoderHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/AVDecoderHandler.cpp.s
.PHONY : src/src/AVDecoderHandler.cpp.s

src/src/DecoderFFmpeg.o: src/src/DecoderFFmpeg.cpp.o
.PHONY : src/src/DecoderFFmpeg.o

# target to build an object file
src/src/DecoderFFmpeg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/DecoderFFmpeg.cpp.o
.PHONY : src/src/DecoderFFmpeg.cpp.o

src/src/DecoderFFmpeg.i: src/src/DecoderFFmpeg.cpp.i
.PHONY : src/src/DecoderFFmpeg.i

# target to preprocess a source file
src/src/DecoderFFmpeg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/DecoderFFmpeg.cpp.i
.PHONY : src/src/DecoderFFmpeg.cpp.i

src/src/DecoderFFmpeg.s: src/src/DecoderFFmpeg.cpp.s
.PHONY : src/src/DecoderFFmpeg.s

# target to generate assembly for a file
src/src/DecoderFFmpeg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/DecoderFFmpeg.cpp.s
.PHONY : src/src/DecoderFFmpeg.cpp.s

src/src/FFmpegMediaEncoder.o: src/src/FFmpegMediaEncoder.cpp.o
.PHONY : src/src/FFmpegMediaEncoder.o

# target to build an object file
src/src/FFmpegMediaEncoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/FFmpegMediaEncoder.cpp.o
.PHONY : src/src/FFmpegMediaEncoder.cpp.o

src/src/FFmpegMediaEncoder.i: src/src/FFmpegMediaEncoder.cpp.i
.PHONY : src/src/FFmpegMediaEncoder.i

# target to preprocess a source file
src/src/FFmpegMediaEncoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/FFmpegMediaEncoder.cpp.i
.PHONY : src/src/FFmpegMediaEncoder.cpp.i

src/src/FFmpegMediaEncoder.s: src/src/FFmpegMediaEncoder.cpp.s
.PHONY : src/src/FFmpegMediaEncoder.s

# target to generate assembly for a file
src/src/FFmpegMediaEncoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/FFmpegMediaEncoder.cpp.s
.PHONY : src/src/FFmpegMediaEncoder.cpp.s

src/src/FFmpegMediaPlayer.o: src/src/FFmpegMediaPlayer.cpp.o
.PHONY : src/src/FFmpegMediaPlayer.o

# target to build an object file
src/src/FFmpegMediaPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/FFmpegMediaPlayer.cpp.o
.PHONY : src/src/FFmpegMediaPlayer.cpp.o

src/src/FFmpegMediaPlayer.i: src/src/FFmpegMediaPlayer.cpp.i
.PHONY : src/src/FFmpegMediaPlayer.i

# target to preprocess a source file
src/src/FFmpegMediaPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/FFmpegMediaPlayer.cpp.i
.PHONY : src/src/FFmpegMediaPlayer.cpp.i

src/src/FFmpegMediaPlayer.s: src/src/FFmpegMediaPlayer.cpp.s
.PHONY : src/src/FFmpegMediaPlayer.s

# target to generate assembly for a file
src/src/FFmpegMediaPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/FFmpegMediaPlayer.cpp.s
.PHONY : src/src/FFmpegMediaPlayer.cpp.s

src/src/MediaDecoderUtility.o: src/src/MediaDecoderUtility.cpp.o
.PHONY : src/src/MediaDecoderUtility.o

# target to build an object file
src/src/MediaDecoderUtility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/MediaDecoderUtility.cpp.o
.PHONY : src/src/MediaDecoderUtility.cpp.o

src/src/MediaDecoderUtility.i: src/src/MediaDecoderUtility.cpp.i
.PHONY : src/src/MediaDecoderUtility.i

# target to preprocess a source file
src/src/MediaDecoderUtility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/MediaDecoderUtility.cpp.i
.PHONY : src/src/MediaDecoderUtility.cpp.i

src/src/MediaDecoderUtility.s: src/src/MediaDecoderUtility.cpp.s
.PHONY : src/src/MediaDecoderUtility.s

# target to generate assembly for a file
src/src/MediaDecoderUtility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/MediaDecoderUtility.cpp.s
.PHONY : src/src/MediaDecoderUtility.cpp.s

src/src/MediaInfoUtility.o: src/src/MediaInfoUtility.cpp.o
.PHONY : src/src/MediaInfoUtility.o

# target to build an object file
src/src/MediaInfoUtility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/MediaInfoUtility.cpp.o
.PHONY : src/src/MediaInfoUtility.cpp.o

src/src/MediaInfoUtility.i: src/src/MediaInfoUtility.cpp.i
.PHONY : src/src/MediaInfoUtility.i

# target to preprocess a source file
src/src/MediaInfoUtility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/MediaInfoUtility.cpp.i
.PHONY : src/src/MediaInfoUtility.cpp.i

src/src/MediaInfoUtility.s: src/src/MediaInfoUtility.cpp.s
.PHONY : src/src/MediaInfoUtility.s

# target to generate assembly for a file
src/src/MediaInfoUtility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/MediaInfoUtility.cpp.s
.PHONY : src/src/MediaInfoUtility.cpp.s

src/src/VRVideoFilter.o: src/src/VRVideoFilter.cpp.o
.PHONY : src/src/VRVideoFilter.o

# target to build an object file
src/src/VRVideoFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/VRVideoFilter.cpp.o
.PHONY : src/src/VRVideoFilter.cpp.o

src/src/VRVideoFilter.i: src/src/VRVideoFilter.cpp.i
.PHONY : src/src/VRVideoFilter.i

# target to preprocess a source file
src/src/VRVideoFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/VRVideoFilter.cpp.i
.PHONY : src/src/VRVideoFilter.cpp.i

src/src/VRVideoFilter.s: src/src/VRVideoFilter.cpp.s
.PHONY : src/src/VRVideoFilter.s

# target to generate assembly for a file
src/src/VRVideoFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/VRVideoFilter.cpp.s
.PHONY : src/src/VRVideoFilter.cpp.s

src/src/register_types.o: src/src/register_types.cpp.o
.PHONY : src/src/register_types.o

# target to build an object file
src/src/register_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/register_types.cpp.o
.PHONY : src/src/register_types.cpp.o

src/src/register_types.i: src/src/register_types.cpp.i
.PHONY : src/src/register_types.i

# target to preprocess a source file
src/src/register_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/register_types.cpp.i
.PHONY : src/src/register_types.cpp.i

src/src/register_types.s: src/src/register_types.cpp.s
.PHONY : src/src/register_types.s

# target to generate assembly for a file
src/src/register_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GDExtensionTemplate.dir/build.make CMakeFiles/GDExtensionTemplate.dir/src/src/register_types.cpp.s
.PHONY : src/src/register_types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... templates"
	@echo "... GDExtensionTemplate"
	@echo "... godot-cpp"
	@echo "... src/src/AVDecoderHandler.o"
	@echo "... src/src/AVDecoderHandler.i"
	@echo "... src/src/AVDecoderHandler.s"
	@echo "... src/src/DecoderFFmpeg.o"
	@echo "... src/src/DecoderFFmpeg.i"
	@echo "... src/src/DecoderFFmpeg.s"
	@echo "... src/src/FFmpegMediaEncoder.o"
	@echo "... src/src/FFmpegMediaEncoder.i"
	@echo "... src/src/FFmpegMediaEncoder.s"
	@echo "... src/src/FFmpegMediaPlayer.o"
	@echo "... src/src/FFmpegMediaPlayer.i"
	@echo "... src/src/FFmpegMediaPlayer.s"
	@echo "... src/src/MediaDecoderUtility.o"
	@echo "... src/src/MediaDecoderUtility.i"
	@echo "... src/src/MediaDecoderUtility.s"
	@echo "... src/src/MediaInfoUtility.o"
	@echo "... src/src/MediaInfoUtility.i"
	@echo "... src/src/MediaInfoUtility.s"
	@echo "... src/src/VRVideoFilter.o"
	@echo "... src/src/VRVideoFilter.i"
	@echo "... src/src/VRVideoFilter.s"
	@echo "... src/src/register_types.o"
	@echo "... src/src/register_types.i"
	@echo "... src/src/register_types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /media/zhuelly/Project/GodotProject/elly_videoplayer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

