/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121328-ge05f8acabf-20251005"
#endif /* AVUTIL_FFVERSION_H */
